### ISSUE TITLE
Failed to load the atomdo package

### ISSUE THREAD

**Issue by willfanguy** [makiwara/atomdo#7]
[Enter steps to reproduce:]

1. Install `atomdo` package

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [atomdo](https://github.com/makiwara/atomdo) package 0.8.0

### Stack Trace

Failed to load the atomdo package

```
At Cannot find module 'undefined/node_modules/season/lib/cson.js'

Error: Cannot find module 'undefined/node_modules/season/lib/cson.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atomdo/lib/atomdo.coffee:4:8)
    at /packages/atomdo/lib/atomdo.coffee:1:1)
    at /packages/atomdo/lib/atomdo.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -1:44.3.0 core:move-left (input.hidden-input)
     -1:43.5.0 core:backspace (input.hidden-input)
     -0:16.8.0 settings-view:open (input.hidden-input)
     -0:13.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-html-preview 0.2.5 
atom-material-syntax 1.0.8 
atomdo 0.8.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.3.0 
file-icons 2.1.21 
foldingtext-markdown 1.3.2 
highlight-selected 0.13.1 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-writer 2.7.3 
minimap 4.29.8 
newbound-dark-syntax 1.1.0 
pigments 0.40.2 
tasks 2.10.1 
tool-bar 1.1.7 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.3.1 
wordcount 3.0.0 
```

**Comment by mrmikee** [comment]
Same issue with Ubuntu Linux.

[Enter steps to reproduce:]

1. Install `atomdo` package using atom gui

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.2
**Thrown From**: [atomdo](https://github.com/makiwara/atomdo) package 0.8.0


### Stack Trace

Failed to load the atomdo package

```
At Cannot find module 'undefined/node_modules/season/lib/cson.js'

Error: Cannot find module 'undefined/node_modules/season/lib/cson.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/snap/atom/214/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/atomdo/lib/atomdo.coffee:4:8)
    at /packages/atomdo/lib/atomdo.coffee:1:1)
    at /packages/atomdo/lib/atomdo.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:1:639511)
    at Package.requireMainModule (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:2932767)
    at measure (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:2919478)
    at Package.measure (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at Package.load (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:2919051)
    at PackageManager.loadAvailablePackage (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:381323)
    at PackageManager.loadPackage (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:380051)
    at PackageManager.activatePackage (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:382555)
    at /snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:917000
    at r (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at e.bufferStream (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:1037812)
    at Socket.e.on (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
```

### Non-Core Packages

```
atomdo 0.8.0 
jira-timesheet 0.2.0 
```
